// ns-3 implementation of LEGOSim's Phase-2 bench -> delayInfo contract.
//
// This program deliberately does not carry PipeComm payloads.  PipeComm is
// LEGOSim's functional data path; Phase 2 receives only the communication
// trace generated by Phase 1 and returns simulated-cycle delays for the next
// conservative synchronization round.

#include "ns3/applications-module.h"
#include "ns3/core-module.h"
#include "ns3/internet-module.h"
#include "ns3/network-module.h"
#include "ns3/point-to-point-module.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <map>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

using namespace ns3;

namespace {

constexpr long kSpecialDescriptorMask = 0xF0000;
constexpr long kBarrier = 0x20000;
constexpr long kLock = 0x40000;
constexpr long kUnlock = 0x80000;

/** A packet tag used to join ns-3 frame events to a LEGOSim trace record. */
class TraceFragmentTag : public Tag {
  public:
    TraceFragmentTag() = default;
    TraceFragmentTag(uint32_t trace_id, uint32_t fragment_index, bool acknowledgement)
        : trace_id_(trace_id), fragment_index_(fragment_index), acknowledgement_(acknowledgement) {}

    static TypeId GetTypeId() {
        static TypeId tid = TypeId("chipsystemsim::TraceFragmentTag")
                                .SetParent<Tag>()
                                .SetGroupName("Network")
                                .AddConstructor<TraceFragmentTag>();
        return tid;
    }

    TypeId GetInstanceTypeId() const override { return GetTypeId(); }
    uint32_t GetSerializedSize() const override { return 9; }
    void Serialize(TagBuffer buffer) const override {
        buffer.WriteU32(trace_id_);
        buffer.WriteU32(fragment_index_);
        buffer.WriteU8(acknowledgement_ ? 1 : 0);
    }
    void Deserialize(TagBuffer buffer) override {
        trace_id_ = buffer.ReadU32();
        fragment_index_ = buffer.ReadU32();
        acknowledgement_ = buffer.ReadU8() != 0;
    }
    void Print(std::ostream& output) const override {
        output << "trace=" << trace_id_ << " fragment=" << fragment_index_
               << " ack=" << acknowledgement_;
    }

    uint32_t TraceId() const { return trace_id_; }
    uint32_t FragmentIndex() const { return fragment_index_; }
    bool IsAcknowledgement() const { return acknowledgement_; }

  private:
    uint32_t trace_id_ = 0;
    uint32_t fragment_index_ = 0;
    bool acknowledgement_ = false;
};

NS_OBJECT_ENSURE_REGISTERED(TraceFragmentTag);

struct BenchRecord {
    uint64_t source_cycle = 0;
    uint64_t destination_cycle = 0;
    uint32_t source = 0;
    uint32_t destination = 0;
    uint64_t flits = 0;
    long descriptor = 0;
};

struct DirectionState {
    uint32_t source = 0;
    uint32_t destination = 0;
    uint32_t fragments = 0;
    std::set<uint32_t> transmitted;
    std::set<uint32_t> received;
    int64_t transmit_finish_ns = -1;
    int64_t arrival_ns = -1;
};

struct TraceState {
    BenchRecord bench;
    uint32_t model_destination = 0;
    bool special = false;
    DirectionState forward;
    DirectionState acknowledgement;
    bool acknowledgement_scheduled = false;
};

uint64_t CeilDivide(uint64_t numerator, uint64_t denominator) {
    return (numerator + denominator - 1) / denominator;
}

uint64_t CeilNanosecondsToCycles(int64_t nanoseconds, uint64_t cycle_ns) {
    if (nanoseconds <= 0) {
        return 0;
    }
    return CeilDivide(static_cast<uint64_t>(nanoseconds), cycle_ns);
}

uint64_t ParsePositive(const std::string& text, const std::string& name) {
    std::size_t parsed = 0;
    const unsigned long long value = std::stoull(text, &parsed, 10);
    if (parsed != text.size() || value == 0) {
        throw std::runtime_error(name + " must be a positive integer");
    }
    return value;
}

std::vector<std::pair<uint32_t, uint32_t>> ReadTopology(const std::string& path) {
    std::ifstream input(path);
    if (!input) {
        throw std::runtime_error("cannot open topology: " + path);
    }
    const std::regex node_number("([0-9]+)");
    std::set<std::pair<uint32_t, uint32_t>> deduplicated;
    std::string line;
    while (std::getline(input, line)) {
        if (line.find("--") == std::string::npos) {
            continue;
        }
        std::vector<uint32_t> nodes;
        for (std::sregex_iterator item(line.begin(), line.end(), node_number), end; item != end;
             ++item) {
            nodes.push_back(static_cast<uint32_t>(std::stoul((*item)[1].str())));
        }
        for (std::size_t index = 1; index < nodes.size(); ++index) {
            if (nodes[index - 1] == nodes[index]) {
                continue;
            }
            const auto edge = std::minmax(nodes[index - 1], nodes[index]);
            deduplicated.insert(edge);
        }
    }
    if (deduplicated.empty()) {
        throw std::runtime_error("topology contains no undirected '--' edges: " + path);
    }
    return {deduplicated.begin(), deduplicated.end()};
}

std::map<uint32_t, uint32_t> ReadWorkerRouting(const std::string& path, uint32_t nodes) {
    std::ifstream input(path);
    if (!input) {
        throw std::runtime_error("cannot open worker routing: " + path);
    }
    const uint32_t width = static_cast<uint32_t>(std::sqrt(nodes));
    if (width == 0 || width * width != nodes) {
        throw std::runtime_error("counterfactual worker routing requires a square chiplet topology");
    }
    const std::string content((std::istreambuf_iterator<char>(input)), std::istreambuf_iterator<char>());
    // ``routing.json`` has a deliberately small stable schema. Reading the
    // coordinate map directly avoids adding a JSON library to this standalone
    // ns-3 adapter executable.
    const std::regex coordinate_slot("\\\"([0-9]+),([0-9]+)\\\"\\s*:\\s*([0-9]+)");
    std::map<uint32_t, uint32_t> slots;
    for (std::sregex_iterator item(content.begin(), content.end(), coordinate_slot), end; item != end;
         ++item) {
        const uint32_t x = static_cast<uint32_t>(std::stoul((*item)[1].str()));
        const uint32_t y = static_cast<uint32_t>(std::stoul((*item)[2].str()));
        const uint32_t slot = static_cast<uint32_t>(std::stoul((*item)[3].str()));
        if (x >= width || y >= width) {
            throw std::runtime_error("worker routing contains a coordinate outside the chiplet topology");
        }
        const uint32_t node = y * width + x;
        const auto inserted = slots.emplace(node, slot);
        if (!inserted.second && inserted.first->second != slot) {
            throw std::runtime_error("worker routing maps one chiplet to multiple workers");
        }
    }
    if (slots.empty()) {
        throw std::runtime_error("worker routing has no coordinate_to_worker_slot entries");
    }
    return slots;
}

std::vector<BenchRecord> ReadBench(const std::string& path) {
    std::ifstream input(path);
    if (!input) {
        throw std::runtime_error("cannot open bench trace: " + path);
    }
    std::vector<BenchRecord> records;
    BenchRecord record;
    while (input >> record.source_cycle >> record.destination_cycle >> record.source >>
           record.destination >> record.flits >> record.descriptor) {
        if (record.flits == 0) {
            throw std::runtime_error("bench record has zero flits");
        }
        records.push_back(record);
    }
    if (!input.eof()) {
        throw std::runtime_error("invalid bench trace record in " + path);
    }
    return records;
}

bool IsSpecial(long descriptor) {
    return (descriptor & kSpecialDescriptorMask) != 0;
}

uint32_t RoutingDestination(const BenchRecord& record) {
    // Match PopNet's synchronization-protocol behavior: barrier/lock traffic
    // is routed to the coordination node, while the delayInfo key still keeps
    // LEGOSim's original destination so the manager can match the command.
    if (record.descriptor & (kBarrier | kLock | kUnlock)) {
        return 0;
    }
    return record.destination;
}

class PhaseTwoSimulator {
  public:
    PhaseTwoSimulator(std::vector<BenchRecord> bench, std::vector<std::pair<uint32_t, uint32_t>> edges,
                      uint32_t nodes, uint64_t cycle_ns, uint64_t flit_bytes,
                      uint64_t max_datagram_bytes, const std::string& link_rate,
                      uint64_t link_delay_ns, uint64_t queue_packets,
                      std::map<uint32_t, uint32_t> worker_slots,
                      bool localize_cross_worker_network)
        : cycle_ns_(cycle_ns),
          flit_bytes_(flit_bytes),
          max_datagram_bytes_(max_datagram_bytes),
          link_rate_(link_rate),
          link_delay_ns_(link_delay_ns),
          worker_slots_(std::move(worker_slots)),
          localize_cross_worker_network_(localize_cross_worker_network) {
        if (nodes == 0) {
            throw std::runtime_error("--nodes must be positive");
        }
        nodes_.Create(nodes);
        InternetStackHelper internet;
        internet.Install(nodes_);

        PointToPointHelper point_to_point;
        point_to_point.SetDeviceAttribute("DataRate", DataRateValue(DataRate(link_rate_)));
        point_to_point.SetChannelAttribute("Delay", TimeValue(NanoSeconds(link_delay_ns_)));
        point_to_point.SetDeviceAttribute("Mtu", UintegerValue(static_cast<uint32_t>(max_datagram_bytes_ + 128)));
        point_to_point.SetQueue("ns3::DropTailQueue<Packet>", "MaxSize",
                                QueueSizeValue(QueueSize(std::to_string(queue_packets) + "p")));

        node_addresses_.resize(nodes);
        uint32_t subnet = 0;
        for (const auto& edge : edges) {
            if (edge.first >= nodes || edge.second >= nodes) {
                throw std::runtime_error("topology edge references a node outside --nodes");
            }
            if (subnet >= 254 * 254) {
                throw std::runtime_error("topology has too many point-to-point links");
            }
            NetDeviceContainer devices = point_to_point.Install(nodes_.Get(edge.first), nodes_.Get(edge.second));
            const uint32_t middle_octet = subnet / 254;
            const uint32_t final_octet = subnet % 254;
            std::ostringstream base;
            base << "10." << (middle_octet + 1) << "." << (final_octet + 1) << ".0";
            Ipv4AddressHelper addresses;
            addresses.SetBase(base.str().c_str(), "255.255.255.252");
            Ipv4InterfaceContainer interfaces = addresses.Assign(devices);
            if (node_addresses_[edge.first] == Ipv4Address()) {
                node_addresses_[edge.first] = interfaces.GetAddress(0);
            }
            if (node_addresses_[edge.second] == Ipv4Address()) {
                node_addresses_[edge.second] = interfaces.GetAddress(1);
            }
            for (uint32_t endpoint = 0; endpoint < devices.GetN(); ++endpoint) {
                const uint32_t node_id = devices.Get(endpoint)->GetNode()->GetId();
                devices.Get(endpoint)->TraceConnectWithoutContext(
                    "PhyTxEnd", MakeCallback(&PhaseTwoSimulator::OnTransmitEnd, this, node_id));
            }
            ++subnet;
        }
        for (uint32_t node = 0; node < nodes; ++node) {
            if (node_addresses_[node] == Ipv4Address()) {
                throw std::runtime_error("topology leaves node " + std::to_string(node) + " disconnected");
            }
        }
        Ipv4GlobalRoutingHelper::PopulateRoutingTables();

        receivers_.resize(nodes);
        for (uint32_t node = 0; node < nodes; ++node) {
            receivers_[node] = Socket::CreateSocket(nodes_.Get(node), UdpSocketFactory::GetTypeId());
            receivers_[node]->Bind(InetSocketAddress(Ipv4Address::GetAny(), PortFor(node)));
            receivers_[node]->SetRecvCallback(MakeCallback(&PhaseTwoSimulator::OnReceive, this, node));
        }

        states_.reserve(bench.size());
        for (const BenchRecord& record : bench) {
            if (record.source >= nodes || record.destination >= nodes) {
                throw std::runtime_error("bench record references a node outside --nodes");
            }
            TraceState state;
            state.bench = record;
            state.model_destination = RoutingDestination(record);
            state.special = IsSpecial(record.descriptor);
            state.forward.source = record.source;
            state.forward.destination = state.model_destination;
            state.forward.fragments = FragmentCount(record.flits * flit_bytes_);
            if (state.special) {
                state.acknowledgement.source = state.model_destination;
                state.acknowledgement.destination = record.source;
                state.acknowledgement.fragments = FragmentCount(flit_bytes_);
            }
            states_.push_back(state);
        }
    }

    void Run() {
        for (uint32_t trace_id = 0; trace_id < states_.size(); ++trace_id) {
            const TraceState& state = states_[trace_id];
            const uint64_t start_ns = state.bench.source_cycle * cycle_ns_;
            Simulator::Schedule(NanoSeconds(start_ns), &PhaseTwoSimulator::SendDirection, this, trace_id, false);
        }
        Simulator::Run();
        Simulator::Destroy();
        for (uint32_t trace_id = 0; trace_id < states_.size(); ++trace_id) {
            const TraceState& state = states_[trace_id];
            if (state.forward.transmit_finish_ns < 0 || state.forward.arrival_ns < 0) {
                throw std::runtime_error("ns-3 did not complete forward transaction " + std::to_string(trace_id));
            }
            if (state.special && (state.acknowledgement.transmit_finish_ns < 0 ||
                                  state.acknowledgement.arrival_ns < 0)) {
                throw std::runtime_error("ns-3 did not complete acknowledgement " +
                                         std::to_string(trace_id));
            }
        }
    }

    void WriteDelayInfo(const std::string& path) const {
        std::ofstream output(path, std::ios::trunc);
        if (!output) {
            throw std::runtime_error("cannot write delayInfo: " + path);
        }
        for (const TraceState& state : states_) {
            const bool localized = IsLocalizedCrossWorker(state);
            const int64_t start_ns = static_cast<int64_t>(state.bench.source_cycle * cycle_ns_);
            const uint64_t forward_source_delay =
                CeilNanosecondsToCycles(state.forward.transmit_finish_ns - start_ns, cycle_ns_);
            const uint64_t forward_destination_delay =
                CeilNanosecondsToCycles(state.forward.arrival_ns - start_ns, cycle_ns_);
            output << state.bench.source_cycle << ' ' << state.bench.source << ' ' << state.bench.destination
                   << ' ' << state.bench.descriptor << ' ';
            if (localized) {
                // This is a timing-only counterfactual. The original
                // PipeComm transaction still runs, preserving data and
                // protocol ordering, but it adds no simulated network delay.
                output << (state.special ? "4 0 0 0 0\n" : "2 0 0\n");
                continue;
            }
            if (!state.special) {
                output << 2 << ' ' << forward_source_delay << ' ' << forward_destination_delay << '\n';
                continue;
            }
            const int64_t acknowledgement_start_ns =
                std::max<int64_t>(state.forward.arrival_ns,
                                  static_cast<int64_t>(state.bench.destination_cycle * cycle_ns_));
            const uint64_t acknowledgement_source_delay = CeilNanosecondsToCycles(
                state.acknowledgement.transmit_finish_ns - acknowledgement_start_ns, cycle_ns_);
            const uint64_t acknowledgement_destination_delay = CeilNanosecondsToCycles(
                state.acknowledgement.arrival_ns - acknowledgement_start_ns, cycle_ns_);
            output << 4 << ' ' << forward_source_delay << ' ' << forward_destination_delay << ' '
                   << acknowledgement_source_delay << ' ' << acknowledgement_destination_delay << '\n';
        }
    }

    void WriteMetricsCsv(const std::string& path) const {
        std::ofstream output(path, std::ios::trunc);
        if (!output) {
            throw std::runtime_error("cannot write metrics CSV: " + path);
        }
        output << "trace_id,src_node,dst_node,model_dst_node,descriptor,special,flits,payload_bytes,"
                  "src_cycle,dst_cycle,forward_tx_finish_cycle,forward_arrival_cycle,"
                  "source_sync_advance_cycles,destination_network_delay_cycles,"
                  "destination_sync_block_cycles,localized_cross_worker,"
                  "ack_tx_finish_cycle,ack_arrival_cycle\n";
        for (uint32_t id = 0; id < states_.size(); ++id) {
            const TraceState& state = states_[id];
            const bool localized = IsLocalizedCrossWorker(state);
            const int64_t start_ns = static_cast<int64_t>(state.bench.source_cycle * cycle_ns_);
            const uint64_t forward_tx_cycle = localized
                                                  ? state.bench.source_cycle
                                                  : CeilNanosecondsToCycles(state.forward.transmit_finish_ns, cycle_ns_);
            const uint64_t forward_arrival_cycle = localized
                                                       ? state.bench.source_cycle
                                                       : CeilNanosecondsToCycles(state.forward.arrival_ns, cycle_ns_);
            const uint64_t source_delay = localized
                                              ? 0
                                              : CeilNanosecondsToCycles(state.forward.transmit_finish_ns - start_ns,
                                                                        cycle_ns_);
            const uint64_t destination_delay = localized
                                                   ? 0
                                                   : CeilNanosecondsToCycles(state.forward.arrival_ns - start_ns,
                                                                             cycle_ns_);
            const uint64_t destination_block = localized
                                                   ? 0
                                                   : (state.bench.source_cycle + destination_delay >
                                                              state.bench.destination_cycle
                                                          ? state.bench.source_cycle + destination_delay -
                                                                state.bench.destination_cycle
                                                          : 0);
            output << id << ',' << state.bench.source << ',' << state.bench.destination << ','
                   << state.model_destination << ',' << state.bench.descriptor << ',' << state.special << ','
                   << state.bench.flits << ',' << state.bench.flits * flit_bytes_ << ','
                   << state.bench.source_cycle << ',' << state.bench.destination_cycle << ','
                   << forward_tx_cycle << ',' << forward_arrival_cycle << ',' << source_delay << ','
                   << destination_delay << ',' << destination_block << ',' << localized << ',';
            if (state.special) {
                output << (localized ? 0 : CeilNanosecondsToCycles(state.acknowledgement.transmit_finish_ns,
                                                                    cycle_ns_))
                       << ','
                       << (localized ? 0 : CeilNanosecondsToCycles(state.acknowledgement.arrival_ns, cycle_ns_));
            }
            output << '\n';
        }
    }

    void WriteSummaryJson(const std::string& path) const {
        uint64_t payload_bytes = 0;
        uint64_t special_records = 0;
        uint64_t normal_records = 0;
        uint64_t source_delay_cycles = 0;
        uint64_t destination_delay_cycles = 0;
        uint64_t destination_block_cycles = 0;
        uint64_t localized_cross_worker_records = 0;
        for (const TraceState& state : states_) {
            payload_bytes += state.bench.flits * flit_bytes_;
            special_records += state.special;
            if (!state.special) {
                ++normal_records;
            }
            if (IsLocalizedCrossWorker(state)) {
                ++localized_cross_worker_records;
                continue;
            }
            if (state.special) {
                continue;
            }
            const int64_t start_ns = static_cast<int64_t>(state.bench.source_cycle * cycle_ns_);
            source_delay_cycles += CeilNanosecondsToCycles(state.forward.transmit_finish_ns - start_ns, cycle_ns_);
            destination_delay_cycles += CeilNanosecondsToCycles(state.forward.arrival_ns - start_ns, cycle_ns_);
            const uint64_t forward_delay =
                CeilNanosecondsToCycles(state.forward.arrival_ns - start_ns, cycle_ns_);
            if (state.bench.source_cycle + forward_delay > state.bench.destination_cycle) {
                destination_block_cycles +=
                    state.bench.source_cycle + forward_delay - state.bench.destination_cycle;
            }
        }
        std::ofstream output(path, std::ios::trunc);
        if (!output) {
            throw std::runtime_error("cannot write metrics JSON: " + path);
        }
        output << "{\n"
               << "  \"phase2_backend\": \"ns-3\",\n"
               << "  \"records\": " << states_.size() << ",\n"
               << "  \"normal_records\": " << normal_records << ",\n"
               << "  \"special_records\": " << special_records << ",\n"
               << "  \"payload_bytes\": " << payload_bytes << ",\n"
               << "  \"cycle_ns\": " << cycle_ns_ << ",\n"
               << "  \"flit_bytes\": " << flit_bytes_ << ",\n"
               << "  \"link_rate\": \"" << link_rate_ << "\",\n"
               << "  \"link_delay_ns\": " << link_delay_ns_ << ",\n"
               << "  \"counterfactual_localize_cross_worker_network\": "
               << (localize_cross_worker_network_ ? "true" : "false") << ",\n"
               << "  \"counterfactual_localized_cross_worker_records\": "
               << localized_cross_worker_records << ",\n"
               << "  \"sum_source_sync_delay_cycles\": " << source_delay_cycles << ",\n"
               << "  \"sum_destination_network_delay_cycles\": " << destination_delay_cycles << ",\n"
               << "  \"sum_destination_sync_block_cycles\": " << destination_block_cycles << "\n"
               << "}\n";
    }

  private:
    bool IsLocalizedCrossWorker(const TraceState& state) const {
        if (!localize_cross_worker_network_) {
            return false;
        }
        const auto source = worker_slots_.find(state.bench.source);
        const auto destination = worker_slots_.find(state.bench.destination);
        if (source == worker_slots_.end() || destination == worker_slots_.end()) {
            throw std::runtime_error("worker routing has no slot for a benchmark communication endpoint");
        }
        return source->second != destination->second;
    }

    uint16_t PortFor(uint32_t node) const { return static_cast<uint16_t>(20000 + node); }

    uint32_t FragmentCount(uint64_t bytes) const {
        return static_cast<uint32_t>(std::max<uint64_t>(1, CeilDivide(bytes, max_datagram_bytes_)));
    }

    uint64_t FragmentBytes(uint64_t bytes, uint32_t fragment_index) const {
        const uint64_t offset = static_cast<uint64_t>(fragment_index) * max_datagram_bytes_;
        return std::min(max_datagram_bytes_, bytes - offset);
    }

    DirectionState& Direction(uint32_t trace_id, bool acknowledgement) {
        return acknowledgement ? states_.at(trace_id).acknowledgement : states_.at(trace_id).forward;
    }

    const DirectionState& Direction(uint32_t trace_id, bool acknowledgement) const {
        return acknowledgement ? states_.at(trace_id).acknowledgement : states_.at(trace_id).forward;
    }

    void SendDirection(uint32_t trace_id, bool acknowledgement) {
        TraceState& state = states_.at(trace_id);
        DirectionState& direction = Direction(trace_id, acknowledgement);
        const uint64_t bytes = acknowledgement ? flit_bytes_ : state.bench.flits * flit_bytes_;
        if (direction.source == direction.destination) {
            // A local transfer still consumes one simulator cycle and is
            // represented in delayInfo so that manager ordering is preserved.
            const int64_t completion = Simulator::Now().GetNanoSeconds() + static_cast<int64_t>(cycle_ns_);
            direction.transmit_finish_ns = completion;
            direction.arrival_ns = completion;
            if (!acknowledgement && state.special) {
                ScheduleAcknowledgement(trace_id);
            }
            return;
        }
        Ptr<Socket> sender = Socket::CreateSocket(nodes_.Get(direction.source), UdpSocketFactory::GetTypeId());
        for (uint32_t fragment = 0; fragment < direction.fragments; ++fragment) {
            const uint64_t fragment_bytes = FragmentBytes(bytes, fragment);
            Ptr<Packet> packet = Create<Packet>(static_cast<uint32_t>(fragment_bytes));
            packet->AddPacketTag(TraceFragmentTag(trace_id, fragment, acknowledgement));
            const int result = sender->SendTo(packet, 0, InetSocketAddress(node_addresses_.at(direction.destination),
                                                                            PortFor(direction.destination)));
            if (result < 0) {
                throw std::runtime_error("ns-3 UDP enqueue failed for trace " + std::to_string(trace_id));
            }
        }
    }

    void OnTransmitEnd(uint32_t node, Ptr<const Packet> packet) {
        TraceFragmentTag tag;
        if (!packet->PeekPacketTag(tag)) {
            return;
        }
        DirectionState& direction = Direction(tag.TraceId(), tag.IsAcknowledgement());
        if (node != direction.source || direction.transmit_finish_ns >= 0) {
            return;
        }
        direction.transmitted.insert(tag.FragmentIndex());
        if (direction.transmitted.size() == direction.fragments) {
            direction.transmit_finish_ns = Simulator::Now().GetNanoSeconds();
        }
    }

    void OnReceive(uint32_t node, Ptr<Socket> socket) {
        Address from;
        while (Ptr<Packet> packet = socket->RecvFrom(from)) {
            TraceFragmentTag tag;
            if (!packet->PeekPacketTag(tag)) {
                continue;
            }
            DirectionState& direction = Direction(tag.TraceId(), tag.IsAcknowledgement());
            if (node != direction.destination || direction.arrival_ns >= 0) {
                continue;
            }
            direction.received.insert(tag.FragmentIndex());
            if (direction.received.size() != direction.fragments) {
                continue;
            }
            direction.arrival_ns = Simulator::Now().GetNanoSeconds();
            if (!tag.IsAcknowledgement() && states_.at(tag.TraceId()).special) {
                ScheduleAcknowledgement(tag.TraceId());
            }
        }
    }

    void ScheduleAcknowledgement(uint32_t trace_id) {
        TraceState& state = states_.at(trace_id);
        if (state.acknowledgement_scheduled) {
            return;
        }
        state.acknowledgement_scheduled = true;
        const int64_t target_ns = std::max<int64_t>(
            state.forward.arrival_ns, static_cast<int64_t>(state.bench.destination_cycle * cycle_ns_));
        const int64_t now_ns = Simulator::Now().GetNanoSeconds();
        Simulator::Schedule(NanoSeconds(std::max<int64_t>(0, target_ns - now_ns)),
                            &PhaseTwoSimulator::SendDirection, this, trace_id, true);
    }

    uint64_t cycle_ns_;
    uint64_t flit_bytes_;
    uint64_t max_datagram_bytes_;
    std::string link_rate_;
    uint64_t link_delay_ns_;
    std::map<uint32_t, uint32_t> worker_slots_;
    bool localize_cross_worker_network_ = false;
    NodeContainer nodes_;
    std::vector<Ipv4Address> node_addresses_;
    std::vector<Ptr<Socket>> receivers_;
    std::vector<TraceState> states_;
};

void PrintUsage(const char* program) {
    std::cerr << "Usage: " << program
              << " --bench PATH --delay-info PATH --topology PATH --nodes N [options]\n"
              << "Options:\n"
              << "  --cycle-ns N             simulated duration of one LEGOSim cycle (default: 1)\n"
              << "  --flit-bytes N           bytes represented by one bench flit (default: 32)\n"
              << "  --link-rate RATE         ns-3 point-to-point rate (default: 128Gbps)\n"
              << "  --link-delay-ns N        propagation delay per topology link (default: 1)\n"
              << "  --max-datagram-bytes N   UDP segment payload for a bench transaction (default: 1400)\n"
              << "  --queue-packets N        maximum packets queued per topology link (default: 100000)\n"
              << "  --worker-routing PATH    generated routing.json used by counterfactual mode\n"
              << "  --localize-cross-worker-network  make cross-worker ns-3 timing local and zero-cycle\n"
              << "  --metrics-csv PATH       per-transaction timing records\n"
              << "  --summary-json PATH      aggregate timing summary\n";
}

}  // namespace

int main(int argc, char* argv[]) {
    try {
        std::string bench_path;
        std::string delay_info_path;
        std::string topology_path;
        std::string metrics_csv_path;
        std::string summary_json_path;
        std::string worker_routing_path;
        std::string link_rate = "128Gbps";
        uint32_t nodes = 0;
        uint64_t cycle_ns = 1;
        uint64_t flit_bytes = 32;
        uint64_t link_delay_ns = 1;
        uint64_t max_datagram_bytes = 1400;
        uint64_t queue_packets = 100000;
        bool localize_cross_worker_network = false;

        for (int index = 1; index < argc; ++index) {
            const std::string argument = argv[index];
            const auto require_value = [&](const std::string& name) -> std::string {
                if (++index >= argc) {
                    throw std::runtime_error(name + " requires a value");
                }
                return argv[index];
            };
            if (argument == "--bench") {
                bench_path = require_value(argument);
            } else if (argument == "--delay-info") {
                delay_info_path = require_value(argument);
            } else if (argument == "--topology") {
                topology_path = require_value(argument);
            } else if (argument == "--nodes") {
                nodes = static_cast<uint32_t>(ParsePositive(require_value(argument), argument));
            } else if (argument == "--cycle-ns") {
                cycle_ns = ParsePositive(require_value(argument), argument);
            } else if (argument == "--flit-bytes") {
                flit_bytes = ParsePositive(require_value(argument), argument);
            } else if (argument == "--link-rate") {
                link_rate = require_value(argument);
            } else if (argument == "--link-delay-ns") {
                link_delay_ns = ParsePositive(require_value(argument), argument);
            } else if (argument == "--max-datagram-bytes") {
                max_datagram_bytes = ParsePositive(require_value(argument), argument);
            } else if (argument == "--queue-packets") {
                queue_packets = ParsePositive(require_value(argument), argument);
            } else if (argument == "--worker-routing") {
                worker_routing_path = require_value(argument);
            } else if (argument == "--localize-cross-worker-network") {
                localize_cross_worker_network = true;
            } else if (argument == "--metrics-csv") {
                metrics_csv_path = require_value(argument);
            } else if (argument == "--summary-json") {
                summary_json_path = require_value(argument);
            } else if (argument == "-h" || argument == "--help") {
                PrintUsage(argv[0]);
                return 0;
            } else {
                throw std::runtime_error("unknown argument: " + argument);
            }
        }
        if (bench_path.empty() || delay_info_path.empty() || topology_path.empty() || nodes == 0) {
            PrintUsage(argv[0]);
            return 2;
        }
        if (max_datagram_bytes > 65000) {
            throw std::runtime_error("--max-datagram-bytes must fit in an IPv4 UDP datagram");
        }
        if (localize_cross_worker_network && worker_routing_path.empty()) {
            throw std::runtime_error("--localize-cross-worker-network requires --worker-routing");
        }

        const std::vector<BenchRecord> bench = ReadBench(bench_path);
        const std::vector<std::pair<uint32_t, uint32_t>> edges = ReadTopology(topology_path);
        const std::map<uint32_t, uint32_t> worker_slots = localize_cross_worker_network
                                                              ? ReadWorkerRouting(worker_routing_path, nodes)
                                                              : std::map<uint32_t, uint32_t>{};
        PhaseTwoSimulator simulator(bench, edges, nodes, cycle_ns, flit_bytes, max_datagram_bytes, link_rate,
                                   link_delay_ns, queue_packets, worker_slots,
                                   localize_cross_worker_network);
        simulator.Run();
        simulator.WriteDelayInfo(delay_info_path);
        if (!metrics_csv_path.empty()) {
            simulator.WriteMetricsCsv(metrics_csv_path);
        }
        if (!summary_json_path.empty()) {
            simulator.WriteSummaryJson(summary_json_path);
        }
        std::cout << "ns3-phase2: records=" << bench.size() << " delay_info=" << delay_info_path << '\n';
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "ns3-phase2: " << error.what() << '\n';
        return 1;
    }
}
